### ISSUE TITLE
role engine-install should work even in case of updating to newer version

### ISSUE THREAD

**Issue by pkubica** [rhevm-qe-automation/ovirt-ansible#10]
- should work in case prompting engine-setup again too (without update)
- not tested yet 
- probably it skip based on the existing service

**Comment by pkubica** [comment]
Maybe just modify only these lines in answerfiles and allow to run engine-setup even if health page is accessible:
OSETUP_RPMDISTRO/requireRollback=none:None
OSETUP_RPMDISTRO/enableUpgrade=none:None
- need check

**Comment by KKoukiou** [comment]
engine-setup role is replaced from https://github.com/oVirt/ovirt-ansible-engine-setup, which actually support updates between minor and major releases, thus I am closing this issue.
