### ISSUE TITLE
Run ovirt-guest-agent role as a part of tests

### ISSUE THREAD

**Issue by KKoukiou** [rhevm-qe-automation/ovirt-ansible#103]

**Comment by StLuke** [comment]
fixed by PR #100

**Comment by KKoukiou** [comment]
@StLuke "run ovirt-guest-agent role as a part of tests" is not done in that PR

**Comment by lukas-bednar** [comment]
starting ovirt-guest-agent fails in case it doesn't run on ovirt-vm, there is missing device which agent uses to communicate with engine.
