### ISSUE TITLE
Let the engine-setup to generate password for DB

### ISSUE THREAD

**Issue by lukas-bednar** [rhevm-qe-automation/ovirt-ansible#112]
There are roles which defines password for engine and DWH database.
Please allow to omit this option and let engine to generate this password.

https://github.com/rhevm-qe-automation/ovirt-ansible/pull/111#discussion_r113906739

**Comment by KKoukiou** [comment]
Since role was moved to https://github.com/oVirt/ovirt-ansible-engine-setup this issue got resolved.
