### ISSUE TITLE
Test upgrade

### ISSUE THREAD

**Issue by petr-balogh** [rhevm-qe-automation/ovirt-ansible#116]
Add tests for upgrade between versions 4.0 -> 4.1, 4.1 - > 4.2..
And add some doc / notes about it into ovirt-engine-setup readme.

**Comment by StLuke** [comment]
@petr-balogh Can you propose some steps on this for the GSOC student on this?
Anything special you need?

I would say for sanity these steps would be sufficient. I am considering just an empty engine, as I believe you're question is regarding ansible automation of this.

a) check health page
b) check database status
c) check service (ovirt-engine, ovirt-engine-dwhd and other ovirt related services running before upgrade) status

**Comment by petr-balogh** [comment]
This part is already partially covered by this commit [https://github.com/rhevm-qe-automation/ovirt-ansible/pull/128/commits/04dbc9812d398f51495fe161519954ce0e8dbe30](https://github.com/rhevm-qe-automation/ovirt-ansible/pull/128/commits/04dbc9812d398f51495fe161519954ce0e8dbe30)

and as @StLuke mentioned, some steps could be improved there. I am not sure if we test now status of database, or service. So GSOC could check this and in case these steps are missing, add them..
and there is only upgrade test from version 4.1 to master, so this upgrade test from version 4.0 to 4.1 could be added.

**Comment by tasdikrahman** [comment]
closed by https://github.com/rhevm-qe-automation/ovirt-ansible/commit/97504af42a31e60ebdb380dea767c00118889bec

**Comment by tasdikrahman** [comment]
We can close this issue as it's merged with master with commit hash 97504af
