### ISSUE TITLE
use 'checksum' when fetching repository using 'get_url'

### ISSUE THREAD

**Issue by lukas-bednar** [rhevm-qe-automation/ovirt-ansible#63]

**Comment by lukas-bednar** [comment]
@StLuke @pkubica

**Comment by lukas-bednar** [comment]
'checksum' doesn't solve my problem. I misunderstood the purpose of that parameter ... we need to find diff solution.

**Comment by vkondula** [comment]
solved in #67 (pending on PR) with force parameter
