### ISSUE TITLE
Unable to copy repo file from http server

### ISSUE THREAD

**Issue by landgraf** [rhevm-qe-automation/ovirt-ansible#78]
I run ansible with 
  -e '{"ovirt_repo_file": "http://host.fqdn/rhev.repo", "ovirt_engine_answer_file_type": "4.0_basic"}' playbooks/rhel-host-deploy/config.yml

and see this error:
fatal: [10.35.149.116]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'unicode object' has no attribute 'url'\n\nThe error appears to have been in '/root/provision/ansible/ansible-playbooks/roles/ovirt-deployment/roles/ovirt-common/tasks/main.yml': line 36, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# 1) get repository files\n- name: copy repository files\n  ^ here\n"}

**Comment by lukas-bednar** [comment]
here is example how to use repository from given url:

https://github.com/rhevm-qe-automation/ovirt-ansible/blob/master/roles/ovirt-common/README.md#example-playbook

**Comment by lukas-bednar** [comment]
@landgraf can we close that ?

**Comment by landgraf** [comment]
Yes. Thank you
