### ISSUE TITLE
Add role for engine-rename utility

### ISSUE THREAD

**Issue by pkubica** [rhevm-qe-automation/ovirt-ansible#8]
for changing engine fqdn (backup and restore on different hosts)

**Comment by prodicus** [comment]
Hey @pkubica 

I was wondering where to place the `main.yml` file in. i.e inside an existing role or create new role and then put it inside that.

Also was checking [this doc](https://www.ovirt.org/documentation/how-to/networking/changing-engine-hostname/) as a reference. Would that be the general order of things of how the hostname is changed?

**Comment by tasdikrahman** [comment]
closed by https://github.com/rhevm-qe-automation/ovirt-ansible/pull/132

**Comment by tasdikrahman** [comment]
we can close this issue as it's been merged with master here in this commit d8fe229b6b11c97184cba88fa2956e7ab704873d
