### ISSUE TITLE
Add role for remote DWH installation

### ISSUE THREAD

**Issue by pkubica** [rhevm-qe-automation/ovirt-ansible#9]
- propably need different answerfile

**Comment by StLuke** [comment]
This idea is proposed as GSOC please contact me on resolution

**Comment by prodicus** [comment]
Hey there, 

Was wondering how to get started with this issue. Thanks

cc: @StLuke @pkubica @lukas-bednar

**Comment by StLuke** [comment]
Hi,

sorry for the late response.
I would consider here 2 scenarios.

1. Playbook for installation with remote dwh
  this consist of 2 different flows:
    a) Engine with remote dwh and database of dwh on dwh machine
    b) Engine with remote dwh and database of dwh on 3rd machine - this would be the same as engine instalaltion with remote database for the dwh part

For these I would preferably **extend engine-setup playbook** to have remote-dwh flag set to False by default. If set to true it will require IP of new dwh machine where dwh will be stored. In both cases, local and remote dwh, we should consider that dwh itself can have remote and local database, thus this can follow the flow of engine-setup with remote database of engine.


2. Migration dwh from local machine of engine to remote machine. [1]
This **new playbook** counts with already installed engine with local dwh and moved dwh to this remote server.
[1] http://www.ovirt.org/develop/release-management/features/engine/migration-of-local-dwh-reports-to-remote/ (Article is outdated, reports does not need to be considered)

For testing of these rolls we can use new containers in travis.

**Comment by tasdikrahman** [comment]
@StLuke

For the 2nd case where we have three machines, one for the engine, the other for holding the dwh-db and the 3rd for holding the dwh-service 

I was having a look at this http://www.ovirt.org/documentation/data-warehouse/Migrating_Data_Warehouse_to_a_Separate_Machine/ .

I am trying to setup a 3 VM setup where one would have ovirt-engine, one with the dwh service and the last one having dwh db in the guide above, looks like its targeted for migrating an exisiting `ovirt_engine_history`

what if one wanted to set one from scratch, how should I go about it?

I am thinking the flow to be 

1. setup the engine without the dwh and then create the `ovirt_engine_history` on the 2nd machine (if anyone can point out how?) 

2. Configure the dwhd service to look for these two remote machines on the 3rd VM

Had posted it on the IRC but couldn't get a response

**Comment by StLuke** [comment]
>>> what if one wanted to set one from scratch, how should I go about it?

I would suggest with fresh installation of engine and dwh together,  link you posted is about migration of pre-existing dwh service/db.

>>> 1. setup the engine without the dwh and then create the ovirt_engine_history on the 2nd machine (if anyone can point out how?)
a) On installation of **engine** on machine1 choose to have **dwh on remote machine**.
b) On machine where you want **dwh service** to be installed **install** package **ovirt-engine-dwh-setup**, which will install necessary requirements for DWH service. Afterwards run **engine-setup** and continue with dwh steps to connect this service to preexisting engine on machine1. During this dwh service installation you are able to choose to have **databse of dwh** service located on the **remote** service, thus connected to 3rd machine.

This will set up databse in a way:
engine machine <- dwh service machine <- dwh service database machine

>>> 2. Configure the dwhd service to look for these two remote machines on the 3rd VM
Not sure which two you mean here, I hope they are mentioned in the previous steps.


All these steps are connected to scenario 1. Playbook for installation with remote dwh a) and b). Link you posted for migration is for scenario 2. Migration dwh from local machine of engine to remote machine. 
For this you can either use steps on ovirt mages you mentioned, or some steps are available here: https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.1/html-single/data_warehouse_guide/#Migrating_the_Data_Warehouse_Database_to_a_Separate_Machine

**Comment by tasdikrahman** [comment]
@StLuke I was able to set up a 3 box setup where 

- one contains the `engine` manager and the `engine` db
- 2nd contains the dwh service
- 3rd contains the dwh database holding the `ovirt_engine_history` db on it

Was stuck on some remote connections issues which made it a hard time for me to debug as they were not showing up in any logs but just giving some arcane connection errors (auth was being successful).

Writing the playbooks for the automation part of this. Should I add it to the same PR/playbook or make a new one? 

Thanks

**Comment by tasdikrahman** [comment]
Was closed by 526f0db97554bf26c46cbda7d383118f0a2009f3
