### ISSUE TITLE
Deploy engine and hypervisor on the same host

### ISSUE THREAD

**Issue by xrow** [rhevm-qe-automation/ovirt-ansible#94]
Hi,

I was test driving the installation quite sucessfull. There was only one issue when deploying engine and hypervisor on the same host.

First I ran the ansible roles for the engine and the GUI came up. Second I was able add the a new host over the GUI. After the sucessfully adding the host the engine GUI was offline, because firewalld was off. I turned it on and the gui was working again. 

```
[root@vm01 ~]# systemctl status firewalld.service
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
   Active: active (running) since Do 2016-12-29 09:42:21 CET; 9min ago
     Docs: man:firewalld(1)
 Main PID: 19477 (firewalld)
   CGroup: /system.slice/firewalld.service
           └─19477 /usr/bin/python -Es /usr/sbin/firewalld --nofork --nopid

```
Workaround
```
[root@vm01 ~]# systemctl enable firewalld
Created symlink from /etc/systemd/system/dbus-org.fedoraproject.FirewallD1.service to /usr/lib/systemd/system/firewalld.service.
Created symlink from /etc/systemd/system/basic.target.wants/firewalld.service to /usr/lib/systemd/system/firewalld.service.
[root@vm01 ~]# systemctl start firewalld
```

Possible solution:
Have firewalld on at all times.

Anyway to cirumvent this odd behavior? Is it a bug?

**Comment by mykaul** [comment]
Deploying the Engine and an Hypervisor on the same host is not supported, unless you are running in a hosted-engine setup.

**Comment by xrow** [comment]
@mykaul Thanks a lot for the hint on the hosted-engine. Will give it a try. I guess the ansible setup is not tuned for this setup, but I check it out. Coming from Microsoft Hyper-V it must say this dependency sounds odd. I close the ticket.
